/*
Autor: Juan Carlos Gomez Lopez
Crear Tablas.
*/

--SELECT * FROM v$version; --v21
CREATE TABLE CAT_CATEGORIA (
    ID_CATEGORIA NUMBER(38,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE_CATEGORIA VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,
    ESTATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (ESTATUS IN (0,1)),
    USUARIO_CREACION VARCHAR2(50) DEFAULT USER,
    USUARIO_MODIFICACION VARCHAR2(50) DEFAULT NULL,
    IP_CREACION VARCHAR2(45)  DEFAULT NULL,
    IP_MODIFICACION VARCHAR2(45) DEFAULT NULL,
    VERSION NUMBER DEFAULT 1,
    CONSTRAINT PK_ID_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
);

CREATE OR REPLACE TRIGGER TRG_CAT_CATEGORIA_AUD
BEFORE INSERT OR UPDATE ON CAT_CATEGORIA
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.IP_CREACION      := FN_GET_IP;
        :NEW.USUARIO_CREACION := USER;
        :NEW.FECHA_CREACION   := SYSTIMESTAMP;

    ELSIF UPDATING THEN
        :NEW.IP_MODIFICACION      := FN_GET_IP;
        :NEW.USUARIO_MODIFICACION := USER;
        :NEW.FECHA_MODIFICACION   := SYSTIMESTAMP;
        :NEW.VERSION := NVL(:OLD.VERSION,1) + 1;
    END IF;
END;
/


COMMENT ON TABLE CAT_CATEGORIA IS 'Catalogo maestro de categorias para clasificacion de productos.';
COMMENT ON COLUMN CAT_CATEGORIA.ID_CATEGORIA IS 'Identificador unico de la categoria.';
COMMENT ON COLUMN CAT_CATEGORIA.NOMBRE_CATEGORIA IS 'Nombre descriptivo de la categoria.';
COMMENT ON COLUMN CAT_CATEGORIA.DESCRIPCION IS 'Descripcion funcional o comercial de la categoria.';
COMMENT ON COLUMN CAT_CATEGORIA.FECHA_CREACION IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN CAT_CATEGORIA.FECHA_MODIFICACION IS 'Fecha y hora de ultima modificacion.';
COMMENT ON COLUMN CAT_CATEGORIA.ESTATUS IS 'Indicador logico de estado (TRUE=Activo,FALSE=Inactivo).';
COMMENT ON COLUMN CAT_CATEGORIA.USUARIO_CREACION IS 'Usuario que creo el registro.';
COMMENT ON COLUMN CAT_CATEGORIA.USUARIO_MODIFICACION IS 'Usuario que modifico el registro.';
COMMENT ON COLUMN CAT_CATEGORIA.IP_CREACION IS 'Direccion IP desde donde se creo el registro.';
COMMENT ON COLUMN CAT_CATEGORIA.IP_MODIFICACION IS 'Direccion IP desde donde se modifico el registro.';
COMMENT ON COLUMN CAT_CATEGORIA.VERSION IS 'Numero de version para control de concurrencia optimista.';



/* 1 PRODUCTO TIENE 1 CATEGORIA, Y 1 CATEGORIA PUEDE ESTAR EN MUCHOS PRODUCTOS (1,N)*/
-- (relacion N:M entre venta vs producto)
CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER(38,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE_PRODUCTO VARCHAR2(100) NOT NULL,
    PRECIO NUMBER(12,2) NOT NULL,
    STOCK NUMBER(10) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    ESTATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (ESTATUS IN (0,1)),
    ID_CATEGORIA NUMBER(38,0) NOT NULL,    
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY(ID_PRODUCTO),
    CONSTRAINT FK_CATEGORIA_PRODUCTO
        FOREIGN KEY(ID_CATEGORIA)
        REFERENCES CAT_CATEGORIA(ID_CATEGORIA)
);

COMMENT ON TABLE PRODUCTO IS 'Tabla que almacena los productos disponibles para venta.';
COMMENT ON COLUMN PRODUCTO.ID_PRODUCTO IS 'Identificador unico del producto.';
COMMENT ON COLUMN PRODUCTO.NOMBRE_PRODUCTO IS 'Nombre comercial del producto.';
COMMENT ON COLUMN PRODUCTO.PRECIO IS 'Precio unitario vigente del producto.';
COMMENT ON COLUMN PRODUCTO.STOCK IS 'Cantidad disponible en inventario.';
COMMENT ON COLUMN PRODUCTO.DESCRIPCION IS 'Descripcion tecnica o comercial del producto.';
COMMENT ON COLUMN PRODUCTO.ESTATUS IS 'Indicador logico del estado del producto (1=Disponible,0=No disponible).';
COMMENT ON COLUMN PRODUCTO.ID_CATEGORIA IS 'Referencia a la categoria a la que pertenece el producto.';
COMMENT ON COLUMN PRODUCTO.FECHA_CREACION IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN PRODUCTO.FECHA_MODIFICACION IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE PRODUCTO_BITA (
    ID_PRODUCTO_BITA NUMBER(38,0) GENERATED ALWAYS AS IDENTITY,
    NOMBRE_PRODUCTO VARCHAR2(100) NOT NULL,
    PRECIO NUMBER(12,2) NOT NULL,
    STOCK NUMBER(10) NOT NULL,
    DESCRIPCION VARCHAR2(200) NOT NULL,
    ESTATUS NUMBER(1) DEFAULT 1 NOT NULL CHECK (ESTATUS IN (0,1)),
    ID_CATEGORIA NUMBER(38,0) NOT NULL,    
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,
    IP_CREACION VARCHAR2(45)  DEFAULT NULL,
    IP_MODIFICACION VARCHAR2(45) DEFAULT NULL,
    ACCION VARCHAR2(15) DEFAULT NULL
);

COMMENT ON TABLE PRODUCTO_BITA IS 'Tabla que almacena los productos disponibles para venta.';
COMMENT ON COLUMN PRODUCTO_BITA.ID_PRODUCTO_BITA IS 'Identificador unico del producto.';
COMMENT ON COLUMN PRODUCTO_BITA.NOMBRE_PRODUCTO IS 'Nombre comercial del producto.';
COMMENT ON COLUMN PRODUCTO_BITA.PRECIO IS 'Precio unitario vigente del producto.';
COMMENT ON COLUMN PRODUCTO_BITA.STOCK IS 'Cantidad disponible en inventario.';
COMMENT ON COLUMN PRODUCTO_BITA.DESCRIPCION IS 'Descripcion tecnica o comercial del producto.';
COMMENT ON COLUMN PRODUCTO_BITA.ESTATUS IS 'Indicador logico del estado del producto (1=Disponible,0=No disponible).';
COMMENT ON COLUMN PRODUCTO_BITA.ID_CATEGORIA IS 'Referencia a la categoria a la que pertenece el producto.';
COMMENT ON COLUMN PRODUCTO_BITA.FECHA_CREACION IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN PRODUCTO_BITA.FECHA_MODIFICACION IS 'Fecha y hora de ultima modificacion.';

create trigger TRG_PRODUCTO_BITA
    after insert or update
    on PRODUCTO
    for each row
DECLARE
    V_ACCION VARCHAR2(10);
    V_FECHA_CREACION TIMESTAMP := NULL;
    V_FECHA_MODIFICACION TIMESTAMP := NULL;
    V_IP_CREACION VARCHAR2(45) := NULL;
    V_IP_MODIFICACION VARCHAR2(45) := NULL;
BEGIN
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSTIMESTAMP;
        V_IP_CREACION := FN_GET_IP;
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_MODIFICACION := SYSTIMESTAMP;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;
        V_IP_MODIFICACION  := FN_GET_IP;
    END IF;

    INSERT INTO PRODUCTO_BITA(NOMBRE_PRODUCTO,PRECIO,STOCK,DESCRIPCION,
        ESTATUS,ID_CATEGORIA,FECHA_CREACION,FECHA_MODIFICACION,IP_CREACION, IP_MODIFICACION,ACCION)
        VALUES(
            :NEW.NOMBRE_PRODUCTO,
            :NEW.PRECIO,
            :NEW.STOCK,
            :NEW.DESCRIPCION,
            :NEW.ESTATUS,
            :NEW.ID_CATEGORIA,
            V_FECHA_CREACION,
            V_FECHA_MODIFICACION,
            V_IP_CREACION,
            V_IP_MODIFICACION,
            V_ACCION
        );
END;
/


-- 1 cliente aparece en muchas ventas, pero cada venta es de 1 solo cliente (1:N)
CREATE TABLE CLIENTE (
   ID_CLIENTE NUMBER(38,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    NOMBRE_CLIENTE VARCHAR2(100) NOT NULL,
    APATERNO VARCHAR2(100) NOT NULL,
    AMATERNO VARCHAR2(100) ,
    CORREO VARCHAR2(200) NOT NULL,
    TELEFONO VARCHAR2(50) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,
    ACTIVO NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACTIVO IN (0,1)),
    CONSTRAINT PK_ID_CLIENTE PRIMARY KEY(ID_CLIENTE)
);

COMMENT ON TABLE CLIENTE IS 'Tabla que almacena informacion de clientes.';
COMMENT ON COLUMN CLIENTE.ID_CLIENTE IS 'Identificador unico del cliente.';
COMMENT ON COLUMN CLIENTE.NOMBRE_CLIENTE IS 'Nombre completo o razon social del cliente.';
COMMENT ON COLUMN CLIENTE.APATERNO IS 'Apellido paterno del cliente.';
COMMENT ON COLUMN CLIENTE.AMATERNO IS 'Apellido materno del cliente.';
COMMENT ON COLUMN CLIENTE.CORREO IS 'Correo electronico asociado al cliente.';
COMMENT ON COLUMN CLIENTE.TELEFONO IS 'Telefono asociado al cliente.';
COMMENT ON COLUMN CLIENTE.FECHA_REGISTRO IS 'Fecha y hora de registo en plataforma.';
COMMENT ON COLUMN CLIENTE.FECHA_CREACION IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN CLIENTE.FECHA_MODIFICACION IS 'Fecha y hora de ultima modificacion.';
COMMENT ON COLUMN CLIENTE.ACTIVO IS 'Indicador logico de estado activo en sistema.';

CREATE TABLE CLIENTE_BITA (
   ID_CLIENTE_BITA NUMBER(38,0) GENERATED ALWAYS AS IDENTITY,
    NOMBRE_CLIENTE VARCHAR2(100) NOT NULL,
    APATERNO VARCHAR2(100) NOT NULL,
    AMATERNO VARCHAR2(100) ,
    CORREO VARCHAR2(200) NOT NULL,
    TELEFONO VARCHAR2(50) NOT NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,
    ACTIVO NUMBER(1) DEFAULT 1 NOT NULL CHECK (ACTIVO IN (0,1)),
    IP_CREACION VARCHAR2(45)  DEFAULT NULL,
    IP_MODIFICACION VARCHAR2(45) DEFAULT NULL,
    ACCION VARCHAR2(15) DEFAULT NULL
);

COMMENT ON TABLE CLIENTE_BITA IS 'Tabla que almacena informacion de clientes.';
COMMENT ON COLUMN CLIENTE_BITA.ID_CLIENTE_BITA IS 'Identificador unico del cliente.';
COMMENT ON COLUMN CLIENTE_BITA.NOMBRE_CLIENTE IS 'Nombre completo o razon social del cliente.';
COMMENT ON COLUMN CLIENTE_BITA.APATERNO IS 'Apellido paterno del cliente.';
COMMENT ON COLUMN CLIENTE_BITA.AMATERNO IS 'Apellido materno del cliente.';
COMMENT ON COLUMN CLIENTE_BITA.CORREO IS 'Correo electronico asociado al cliente.';
COMMENT ON COLUMN CLIENTE_BITA.TELEFONO IS 'Telefono asociado al cliente.';
COMMENT ON COLUMN CLIENTE_BITA.FECHA_REGISTRO IS 'Fecha y hora de registo en plataforma.';
COMMENT ON COLUMN CLIENTE_BITA.FECHA_CREACION IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN CLIENTE_BITA.FECHA_MODIFICACION IS 'Fecha y hora de ultima modificacion.';
COMMENT ON COLUMN CLIENTE_BITA.ACTIVO IS 'Indicador logico de estado activo en sistema.';


CREATE OR REPLACE TRIGGER TRG_CLIENTE_BITA
    AFTER INSERT OR UPDATE
    ON CLIENTE
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10);  -- Sin asignación inicial
    V_FECHA_CREACION TIMESTAMP := NULL;
    V_FECHA_MODIFICACION TIMESTAMP := NULL;
    V_IP_CREACION VARCHAR2(45) := NULL;
    V_IP_MODIFICACION VARCHAR2(45) := NULL;
BEGIN
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSTIMESTAMP;
        V_IP_CREACION := FN_GET_IP;
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_MODIFICACION := SYSTIMESTAMP;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;
        V_IP_MODIFICACION := FN_GET_IP;
    END IF;

    INSERT INTO CLIENTE_BITA (
        NOMBRE_CLIENTE, APATERNO, AMATERNO, CORREO, TELEFONO, ACTIVO,
        FECHA_REGISTRO, FECHA_CREACION, FECHA_MODIFICACION,
        IP_CREACION, IP_MODIFICACION, ACCION
    ) VALUES (
        :NEW.NOMBRE_CLIENTE,
        :NEW.APATERNO,
        :NEW.AMATERNO,
        :NEW.CORREO,
        :NEW.TELEFONO,
        :NEW.ACTIVO,
        :NEW.FECHA_REGISTRO,
        V_FECHA_CREACION,
        V_FECHA_MODIFICACION,
        V_IP_CREACION,
        V_IP_MODIFICACION,
        V_ACCION
    );
END;
/

-- (relacion N:M entre venta vs producto)
CREATE TABLE VENTA (
    ID_VENTA NUMBER(38,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ID_CLIENTE NUMBER(38,0) NOT NULL,    
    FECHA_VENTA TIMESTAMP DEFAULT SYSTIMESTAMP ,
    USUARIO_REGISTRO VARCHAR2(200) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,    
    CONSTRAINT PK_ID_VENTA PRIMARY KEY(ID_VENTA),
    CONSTRAINT FK_CLIENTE_VENTA
        FOREIGN KEY(ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE)
);

COMMENT ON TABLE VENTA IS 'Tabla que almacena las ventas realizadas.';
COMMENT ON COLUMN VENTA.ID_VENTA IS 'Identificador unico de la venta.';
COMMENT ON COLUMN VENTA.ID_CLIENTE IS 'Referencia al cliente que realiza la compra.';
COMMENT ON COLUMN VENTA.USUARIO_REGISTRO IS 'Descripcion general de la venta.';
COMMENT ON COLUMN VENTA.FECHA_CREACION IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN VENTA.FECHA_MODIFICACION IS 'Fecha y hora de ultima modificacion.';

CREATE TABLE VENTA_BITA (
    ID_VENTA_BITA NUMBER(38,0) GENERATED ALWAYS AS IDENTITY,
    ID_CLIENTE NUMBER(38,0) NOT NULL,    
    FECHA_VENTA TIMESTAMP DEFAULT SYSTIMESTAMP ,
    USUARIO_REGISTRO VARCHAR2(200) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,
    IP_CREACION VARCHAR2(45)  DEFAULT NULL,
    IP_MODIFICACION VARCHAR2(45) DEFAULT NULL,
    ACCION VARCHAR2(15) DEFAULT NULL
);

COMMENT ON TABLE VENTA_BITA IS 'Tabla que almacena las ventas realizadas.';
COMMENT ON COLUMN VENTA_BITA.ID_VENTA_BITA IS 'Identificador unico de la venta.';
COMMENT ON COLUMN VENTA_BITA.ID_CLIENTE IS 'Referencia al cliente que realiza la compra.';
COMMENT ON COLUMN VENTA_BITA.FECHA_VENTA IS 'Fecha de venta.';
COMMENT ON COLUMN VENTA_BITA.USUARIO_REGISTRO IS 'Descripcion general de la venta.';
COMMENT ON COLUMN VENTA_BITA.FECHA_CREACION IS 'Fecha y hora de creacion del registro.';
COMMENT ON COLUMN VENTA_BITA.FECHA_MODIFICACION IS 'Fecha y hora de ultima modificacion.';

create trigger TRG_VENTA_BITA
    after insert or update
    on VENTA
    for each row
DECLARE
    V_ACCION VARCHAR2(10);
    V_FECHA_CREACION TIMESTAMP  := NULL;
    V_FECHA_MODIFICACION TIMESTAMP  := NULL;
    V_IP_CREACION VARCHAR2(45) := NULL;
    V_IP_MODIFICACION VARCHAR2(45) := NULL;
BEGIN
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSTIMESTAMP ;
        V_IP_CREACION := FN_GET_IP;
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_MODIFICACION := SYSTIMESTAMP ;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;
        V_IP_MODIFICACION  := FN_GET_IP;
    END IF;

    INSERT INTO VENTA_BITA(ID_CLIENTE,FECHA_VENTA,USUARIO_REGISTRO,FECHA_CREACION,FECHA_MODIFICACION
        ,IP_CREACION,IP_MODIFICACION,ACCION)
        VALUES(
             :NEW.ID_CLIENTE
            ,:NEW.FECHA_VENTA
            ,:NEW.USUARIO_REGISTRO
            ,V_FECHA_CREACION
            ,V_FECHA_MODIFICACION
            ,V_IP_CREACION
            ,V_IP_MODIFICACION
            ,V_ACCION
        );
END;
/


CREATE TABLE VENTA_PRODUCTOS(
    ID_VENTA_PRODUCTOS NUMBER(38,0) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ID_VENTA NUMBER(38,0) NOT NULL,
    ID_PRODUCTO NUMBER(38,0) NOT NULL,
    CANTIDAD NUMBER(10) DEFAULT 1 NOT NULL,
    PRECIO_UNITARIO NUMBER(12,2) NOT NULL,
    DESCRIPCION VARCHAR2(100) NOT NULL,
    CANCELADA NUMBER(1) DEFAULT 0 NOT NULL CHECK (CANCELADA IN (0,1)),
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,
    CONSTRAINT PK_ID_VENTA_PRODUCTOS PRIMARY KEY(ID_VENTA_PRODUCTOS),
    CONSTRAINT FK_VENTA
        FOREIGN KEY(ID_VENTA)
        REFERENCES VENTA(ID_VENTA),
    CONSTRAINT FK_PRODUCTO
        FOREIGN KEY(ID_PRODUCTO)
        REFERENCES PRODUCTO(ID_PRODUCTO)
    ,CONSTRAINT UK_VENTA_PRODUCTO UNIQUE (ID_VENTA, ID_PRODUCTO)
);

COMMENT ON TABLE VENTA_PRODUCTOS IS 'Tabla intermedia que relaciona ventas con productos (detalle de venta).';
COMMENT ON COLUMN VENTA_PRODUCTOS.ID_VENTA_PRODUCTOS IS 'Identificador unico del detalle de venta.';
COMMENT ON COLUMN VENTA_PRODUCTOS.ID_VENTA IS 'Referencia a la venta asociada.';
COMMENT ON COLUMN VENTA_PRODUCTOS.ID_PRODUCTO IS 'Referencia al producto vendido.';
COMMENT ON COLUMN VENTA_PRODUCTOS.CANTIDAD IS 'Referencia al producto vendido.';
COMMENT ON COLUMN VENTA_PRODUCTOS.PRECIO_UNITARIO IS 'Referencia al producto vendido.';
COMMENT ON COLUMN VENTA_PRODUCTOS.DESCRIPCION IS 'Descripcion adicional del producto dentro de la venta.';
COMMENT ON COLUMN VENTA_PRODUCTOS.CANCELADA IS 'Muestra si la compra sufrio una cancelacion durante el proceso de venta.';

CREATE TABLE VENTA_PRODUCTOS_BITA(
    ID_VENTA_PRODUCTOS_BITA NUMBER(38,0) GENERATED ALWAYS AS IDENTITY,
    ID_VENTA NUMBER(38,0) NOT NULL,
    ID_PRODUCTO NUMBER(38,0) NOT NULL,
    CANTIDAD NUMBER(10) DEFAULT 1 NOT NULL,
    PRECIO_UNITARIO NUMBER(12,2) NOT NULL,
    DESCRIPCION VARCHAR2(100) NOT NULL,
    CANCELADA NUMBER(1) DEFAULT 0 NOT NULL CHECK (CANCELADA IN (0,1)),
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_MODIFICACION TIMESTAMP DEFAULT NULL,
    IP_CREACION VARCHAR2(45)  DEFAULT NULL,
    IP_MODIFICACION VARCHAR2(45) DEFAULT NULL,
    ACCION VARCHAR2(15) DEFAULT NULL
);

COMMENT ON TABLE VENTA_PRODUCTOS_BITA IS 'Tabla intermedia que relaciona ventas con productos (detalle de venta).';
COMMENT ON COLUMN VENTA_PRODUCTOS_BITA.ID_VENTA_PRODUCTOS_BITA IS 'Identificador unico del detalle de venta.';
COMMENT ON COLUMN VENTA_PRODUCTOS_BITA.ID_VENTA IS 'Referencia a la venta asociada.';
COMMENT ON COLUMN VENTA_PRODUCTOS_BITA.ID_PRODUCTO IS 'Referencia al producto vendido.';
COMMENT ON COLUMN VENTA_PRODUCTOS_BITA.CANTIDAD IS 'Referencia al producto vendido.';
COMMENT ON COLUMN VENTA_PRODUCTOS_BITA.PRECIO_UNITARIO IS 'Referencia al producto vendido.';
COMMENT ON COLUMN VENTA_PRODUCTOS_BITA.DESCRIPCION IS 'Descripcion adicional del producto dentro de la venta.';
COMMENT ON COLUMN VENTA_PRODUCTOS_BITA.CANCELADA IS 'Muestra si la compra sufrio una cancelacion durante el proceso de venta.';

CREATE TRIGGER TRG_VENTA_PRODUCTOS_BITA
    AFTER INSERT OR UPDATE 
    ON VENTA_PRODUCTOS
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(10);
    V_FECHA_CREACION TIMESTAMP  := NULL;
    V_FECHA_MODIFICACION TIMESTAMP  := NULL;
    V_IP_CREACION VARCHAR2(45) := NULL;
    V_IP_MODIFICACION VARCHAR2(45) := NULL;
BEGIN 
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSTIMESTAMP ;
        V_IP_CREACION := FN_GET_IP;
    ELSIF UPDATING THEN
        V_ACCION := 'UPDATE';
        V_FECHA_MODIFICACION := SYSTIMESTAMP;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;
        V_IP_MODIFICACION  := FN_GET_IP;
    END IF;

    INSERT INTO VENTA_PRODUCTOS_BITA(ID_VENTA,ID_PRODUCTO,CANTIDAD,PRECIO_UNITARIO,
            DESCRIPCION,CANCELADA,FECHA_CREACION,FECHA_MODIFICACION,IP_CREACION,IP_MODIFICACION,ACCION)
        VALUES(
             :NEW.ID_VENTA
            ,:NEW.ID_PRODUCTO
            ,:NEW.CANTIDAD
            ,:NEW.PRECIO_UNITARIO
            ,:NEW.DESCRIPCION 
            ,:NEW.CANCELADA 
            ,V_FECHA_CREACION
            ,V_FECHA_MODIFICACION
            ,V_IP_CREACION
            ,V_IP_MODIFICACION
            ,V_ACCION
        );
END;
/

-- Indice FK PRODUCTO -> CATEGORIA
CREATE INDEX IDX_PRODUCTO_ID_CATEGORIA
ON PRODUCTO(ID_CATEGORIA);

-- Indice FK VENTA -> CLIENTE
CREATE INDEX IDX_VENTA_ID_CLIENTE
ON VENTA(ID_CLIENTE);

-- Indice FK VENTA_PRODUCTOS -> VENTA
CREATE INDEX IDX_VP_ID_VENTA
ON VENTA_PRODUCTOS(ID_VENTA);

-- Indice FK VENTA_PRODUCTOS -> PRODUCTO
CREATE INDEX IDX_VP_ID_PRODUCTO
ON VENTA_PRODUCTOS(ID_PRODUCTO);

--Indice Estatus frecuentes
CREATE INDEX IDX_CATEGORIA_ESTATUS ON CAT_CATEGORIA(ESTATUS);
CREATE INDEX IDX_PRODUCTO_ESTATUS ON PRODUCTO(ESTATUS);
CREATE INDEX IDX_CLIENTE_ACTIVO ON CLIENTE(ACTIVO);
CREATE INDEX IDX_VENTA_PRODUCTO_CANCELADA ON VENTA_PRODUCTOS(CANCELADA);

