
--Productos con categoría
create OR REPLACE VIEW VW_PRODUCTOS_CATEGORIA AS
SELECT
    P.ID_PRODUCTO,
    P.NOMBRE_PRODUCTO,
    C.NOMBRE_CATEGORIA
    --P.PRECIO,
    --P.STOCK

FROM PRODUCTO P
JOIN CAT_CATEGORIA C
    ON C.ID_CATEGORIA = P.ID_CATEGORIA
;

SELECT COUNT(*) FROM  PRODUCTO P;


--Ventas con cliente y producto
CREATE OR REPLACE VIEW VW_VENTAS_DETALLE AS
SELECT
    V.ID_VENTA,
    V.NOMBRE_VENTA,
    C.NOMBRE_CLIENTE,
    P.NOMBRE_PRODUCTO,
    VP.CANTIDAD,
    VP.PRECIO_UNITARIO
FROM VENTA V
JOIN CLIENTE C ON C.ID_CLIENTE = V.ID_CLIENTE
JOIN VENTA_PRODUCTOS VP ON VP.ID_VENTA = V.ID_VENTA
JOIN PRODUCTO P ON P.ID_PRODUCTO = VP.ID_PRODUCTO;
