--FUNCIÓN TOTAL VENTA (PUNTO 10)
CREATE OR REPLACE FUNCTION FN_CALCULAR_TOTAL(p_id_venta NUMBER)
RETURN NUMBER
IS
    v_total NUMBER := 0;
BEGIN
    SELECT SUM(CANTIDAD * PRECIO_UNITARIO)
    INTO v_total
    FROM VENTA_PRODUCTOS
    WHERE (p_id_venta = 0 OR ID_VENTA = p_id_venta);

    RETURN NVL(v_total,0);
END;
/


--FUNCIÓN ADICIONAL – IVA 16% (PUNTO 11)

CREATE OR REPLACE FUNCTION FN_CALCULAR_IVA(p_total NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN p_total * 0.16;
END;
/
